import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export const mockData = [
  {"id":1,"name":"Pecan Raisin - Tarts","description":"In hac habitasse platea dictumst.","imageUrl":"http://dummyimage.com/126x100.png/cc0000/ffffff","quantityAvailable":20},
    {"id":2,"name":"Bacon Strip Precooked","description":"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.","imageUrl":"http://dummyimage.com/217x100.png/5fa2dd/ffffff","quantityAvailable":93},
    {"id":3,"name":"Chocolate - Compound Coating","description":"Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.","imageUrl":"http://dummyimage.com/145x100.png/ff4444/ffffff","quantityAvailable":47},
    {"id":4,"name":"Wine - Magnotta - Cab Sauv","description":"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.","imageUrl":"http://dummyimage.com/198x100.png/5fa2dd/ffffff","quantityAvailable":98},
    {"id":5,"name":"Cheese - Grie Des Champ","description":"Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.","imageUrl":"http://dummyimage.com/128x100.png/dddddd/000000","quantityAvailable":47},
    {"id":6,"name":"Honey - Lavender","description":"Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.","imageUrl":"http://dummyimage.com/150x100.png/ff4444/ffffff","quantityAvailable":82},
    {"id":7,"name":"Cups 10oz Trans","description":"Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.","imageUrl":"http://dummyimage.com/130x100.png/cc0000/ffffff","quantityAvailable":11},
    {"id":8,"name":"Sugar - White Packet","description":"In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.","imageUrl":"http://dummyimage.com/188x100.png/cc0000/ffffff","quantityAvailable":51},
    {"id":9,"name":"Ocean Spray - Ruby Red","description":"Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.","imageUrl":"http://dummyimage.com/227x100.png/dddddd/000000","quantityAvailable":31},
    {"id":10,"name":"Chef Hat 25cm","description":"Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.","imageUrl":"http://dummyimage.com/136x100.png/ff4444/ffffff","quantityAvailable":55}
]

